### ISSUE TITLE
Setting up this container

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker-deepnote#1]
Saving links for further reading. Alternatives:
- continuing with DockerHub: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/
- using GitHub container registry: https://blog.codecentric.de/en/2021/03/github-container-registry/

**Comment by ZachNewbery** [comment]
Fixed with commit hash: aab57aedcbaf3530910fe3b53c8db3b1d22c50a3
